### ISSUE TITLE
React 14 and peerDependencies

### ISSUE THREAD

**Issue by TheLudd** [Lapple/react-json-inspector#19]
Did the change to work with react 0.14 break comparability with react 0.13?

If not, could the peerDependency be changed to `>=0.13.0`

If it did, this is a breaking change and should warrant a new major version. 

Currently I cannot use version `5.3.0` with react `0.13.x` but with `5.2.1` I could.

**Comment by Lapple** [comment]
Yes, I think there's at least one breaking change, see [here](https://github.com/Lapple/react-json-inspector/commit/41f54e5e205eec41e6d88ef32894658eea711ac8#diff-6d51238a910fee4ddc7c6ef645a4b996L24).

I will publish 5.4.0 for React 0.13 and 6.0.0 for React 0.14.

**Comment by TheLudd** [comment]
> I will publish 5.4.0 for React 0.13 and 6.0.0 for React 0.14.

Awesome :+1:

**Comment by Lapple** [comment]
Done, please see if it works for you, sorry for inconvenience.

**Comment by TheLudd** [comment]
It works fine. 
Thank you

**Comment by tomatau** [comment]
I'm still seeing this, not sure why:

```
app@0.0.1 /Users/tomatao/Projects/app
├── UNMET PEER DEPENDENCY react@0.14.0
└─┬ react-json-inspector@5.4.0
  ├─┬ debounce@1.0.0
  │ └── date-now@1.0.1
  ├── md5-o-matic@0.1.1
  └── object-assign@2.0.0

npm WARN EPEERINVALID react-json-inspector@5.4.0 requires a peer of react@^0.13.0 but none was installed.
```

I'm on `react@0.14.0`

**Comment by Lapple** [comment]
@tomatau if you are using React 0.14 in the rest of your application, try using `react-json-inspector@6.0.0`, does it work?

**Comment by tomatau** [comment]
That worked thanks.  Shouldn't npm default to the latest version?

**Comment by Lapple** [comment]
Looks like `latest` is the version that was published the latest, hopefully this will get fixed when a next v6 release is ready.
